"""add_file_hash_column

Revision ID: a8d421ac2344
Revises: 5e0f48a21d94
Create Date: 2026-02-15 18:42:24.527402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a8d421ac2344'
down_revision: Union[str, Sequence[str], None] = '5e0f48a21d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_vault', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.alter_column('media_vault', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_media_vault_file_hash'), 'media_vault', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_vault_file_hash'), table_name='media_vault')
    op.alter_column('media_vault', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('media_vault', 'file_hash')
    # ### end Alembic commands ###
