"""Add chunking metadata columns

Revision ID: d14aa56407cf
Revises: a8d421ac2344
Create Date: 2026-02-16 13:22:54.003221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd14aa56407cf'
down_revision: Union[str, Sequence[str], None] = 'a8d421ac2344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_vault', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('media_vault', sa.Column('start_time', sa.Float(), nullable=True))
    op.add_column('media_vault', sa.Column('chunk_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_vault', 'chunk_text')
    op.drop_column('media_vault', 'start_time')
    op.drop_column('media_vault', 'page_number')
    # ### end Alembic commands ###
